name: gaussian_splatting
channels: [pytorch, nvidia, conda-forge]
dependencies:
    - python=3.10
    - pip
    - pytorch=2.1.2
    - torchvision=0.16.2
    - torchaudio=2.1.2
    - pytorch-cuda=11.8
    - tqdm
    - plyfile
    - opencv
    - joblib
